### ISSUE TITLE
Broke something loading pfUI profile ERROR: Interface\AddOns\pfUI\env\fonts.lua:67: attempt to index field 'text' (a nil value)

### ISSUE THREAD

**Issue by joeBwanKenobi** [shagu/pfUI#848]
I was trying to set up pfUI today, exploring the options and I saw there were some pre-made profiles.  I loaded through them and when I tried to load the pfUI profile I was reverted to WoW's interface.  

An error in the chat feed read "ERROR: Interface\AddOns\pfQuest\pfQuest.lua:389: <unnamed>:SetText(): Font not set.

I disabled pfQuest to see if it would work, but I was given this error instead: ERROR: Interface\AddOns\pfUI\env\fonts.lua:67: attempt to index field 'text' (a nil value).

I've deleted / replaced the pfUI and pfQuest folders in AddOns to no avail.  Any ideas?
![pfui-2](https://user-images.githubusercontent.com/3845419/35709335-01568e8a-0780-11e8-8135-86ee41caed64.PNG)
![pufi-1](https://user-images.githubusercontent.com/3845419/35709336-0163a372-0780-11e8-8a6c-7ff572830cf4.PNG)

**Comment by stokbaek** [comment]
This should be fixed in last commit. Are you sure you are using newest version?

**Comment by joeBwanKenobi** [comment]
Yeh I had been using a developmental build, but I removed that and specifically went to the "Latest Version" link, downloaded that one and installed.  Still having the same issue.  Are there files elsewhere I might need to delete?

**Comment by joeBwanKenobi** [comment]
Also, if there are any log files that would be useful please let me know and I will get them posted.

**Comment by shagu** [comment]
This bug is already fixed with this commit: https://github.com/shagu/pfUI/commit/2ab74b1f3d474d0cc9ef1ab64aa9f39ecac57ce7 

Please update pfUI to the latest version and reset your broken config with this command: `/run pfUI_config = {}` followed by a `/rl`.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/issues/845

**Comment by joeBwanKenobi** [comment]
Excellent, ran those commands and it's back to normal.  Thank you for your help @shagu.
